Add "set -e" to script so we don't run on blindly when something fails.

diff --git a/debian/gen-debian-files b/debian/gen-debian-files
--- a/debian/gen-debian-files
+++ b/debian/gen-debian-files
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e  # Fail if any command fails.
+
 [ $# -ne 0 ] && {
     echo "usage: $(basename $0)" >&2
     exit 1
