Fixed cmake file and script exit status test.

diff --git a/test/abi-compliance/check-abi-compliance.sh.in b/test/abi-compliance/check-abi-compliance.sh.in
--- a/test/abi-compliance/check-abi-compliance.sh.in
+++ b/test/abi-compliance/check-abi-compliance.sh.in
@@ -28,7 +28,7 @@ set -x
 echo "build type: " "@CMAKE_BUILD_TYPE@"
 echo "flags: " "@CMAKE_CXX_FLAGS@"
 echo "debug flags: " "@CMAKE_CXX_FLAGS_DEBUG@"
-exit 0
+
 progname=$(basename $0)
 
 distro=$(lsb_release -c -s)
@@ -50,8 +50,21 @@ cur_abi=${libname}_@UNITY_SCOPES_FULL_VERSION@.abi.xml
 report=${libname}_@UNITY_SCOPES_FULL_VERSION@_abi-report.txt
 
 # Compare against the base ABI.
-abidiff ${base_abi} ${cur_abi} >${report} 2>&1
+# TODO: Suppressions current do not work with abidiff for added files, so we use a work-around
+#       to suppress all harmless changes for now, and check whether we got empty output instead.
+#abidiff --suppressions ${CMAKE_CURRENT_SOURCE_DIR}/suppressions ${base_abi} ${cur_abi} >${report} 2>&1
+abidiff --no-unreferenced-symbols --changed-fns --deleted-fns --deleted-vars --changed-vars \
+    ${base_abi} ${cur_abi} >${report} 2>&1
 status=$?
+
+# TODO: The exit status test below is not reliable with 1.0.rc2 (https://sourceware.org/bugzilla/show_bug.cgi?id=19596).
+#       We rely on the report size for the time being.
+[ $status -ge 4 -a -s $report ] && {
+    echo "${progname}: ERROR: Incompatible ABI!" >&2
+    cat ${report} >&2
+    exit 8
+}
+exit 0  # TODO
 
 # Incompatible changes found.
 [ $status -ge 8 ] && {
@@ -62,7 +75,7 @@ status=$?
 
 # Compatible changes found.
 [ $status -ge 4 ] && {
-    echo "${progname}: ABI is compatible with changes, see $report for details."
+    echo "${progname}: ABI has possibly incompatible changes, see $report for details."
     exit 0
 }
 
